project:
  type: website
  output-dir: docs
  
website:
  title: "MSc Thesis"

  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
    

toc: true
number-sections: true
bibliography: references.bib  
  
    



